### ISSUE TITLE
Comentarios avances 2

### ISSUE THREAD

**Issue by AliciaMstt** [AridaiHari/Proyecto-Final-BioInfo-2018_II#2]
Me parece que van muy bien tus avences. 

Tu texto tiene varias faltas de ortografía y TYpos, además te faltó poner en cursivas algunos nombres científicios y géneros. Por favor arregla eso.

**Comment by AridaiHari** [comment]
Ok, ya revisé la ortografía y los errores de tipos. Me parece que algunos errores de "tipos" se debe a que algunos símbolos que haroopad reconoce el github no. Al menos es el caso de ==*ipyrad*==, que subraya el texto de amarillo. Ocurre lo mismo con los colores.

**Comment by AliciaMstt** [comment]
Creo que en haroopad hay en algún lugar una opción para asegurarte que estés usando github flavored markdown. Si no, al subirlo a github revisa que se vea como lo esperas y corrige de ser necesario.
